### PR TITLE
adding the first basic  css codes

### PR DESCRIPTION
**Pull request by dusengepeggy**
Here I started doing the css .
Here is what needs to be done :

-  finalisation of the css

### CODE REVIEW

**Comment by umugabe** [comment]
well done!

**Review by umugabe — APPROVED** [review]

**Review by dosite-cyiza — APPROVED** [review]
keep working

**Comment by Umubyeyi-Marie** [comment]
Good

**Review by Umubyeyi-Marie — APPROVED** [review]

**Review by dusengepeggy — COMMENTED** [review]
Good

**Review by dusengepeggy — COMMENTED** [review]
U added nothing

**Pull request merged**
